apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"alert-service"},"name":"alert-service","namespace":"default"},"spec":{"ports":[{"port":9003,"protocol":"TCP","targetPort":9003}],"selector":{"app":"alert-service"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-08-17T15:17:38Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: alert-service
  name: alert-service
  namespace: default
  resourceVersion: "145285"
  uid: 4990f5d7-f8f0-485a-9e98-934ecb6c430c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.163.64
  clusterIPs:
  - 10.100.163.64
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30870
    port: 9003
    protocol: TCP
    targetPort: 9003
  selector:
    app: alert-service
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a4990f5d7f8f0485a9e98934ecb6c430-1325408113.us-east-1.elb.amazonaws.com
