apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"user-service"},"name":"user-service","namespace":"default"},"spec":{"ports":[{"port":9002,"protocol":"TCP","targetPort":9002}],"selector":{"app":"user-service"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-08-17T06:00:37Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: user-service
  name: user-service
  namespace: default
  resourceVersion: "107717"
  uid: 34876b11-87a7-4706-9c29-39a34ffa856a
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.226.31
  clusterIPs:
  - 10.100.226.31
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31879
    port: 9002
    protocol: TCP
    targetPort: 9002
  selector:
    app: user-service
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a34876b1187a747069c2939a34ffa856-477241358.us-east-1.elb.amazonaws.com
