apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
        - name: alert-service
          image: pabasarasamarakoondocker1945/alert-service:latest
          ports:
            - containerPort: 9003
          env:
            - name: DATABASE_URL
              value: postgresql://alert_service_admin:1234@alert-db:5432/alert_service_db
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: CORS_ORIGINS
              value: "http://127.0.0.1:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: alert-service
spec:
  selector:
    app: alert-service
  ports:
    - port: 9003
      targetPort: 9003
  type: NodePort 