apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-db
  template:
    metadata:
      labels:
        app: alert-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: alert_service_admin
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: alert_service_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: alert-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: alert-db
spec:
  selector:
    app: alert-db
  ports:
    - port: 5432
      targetPort: 5432
