apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bus-service
  template:
    metadata:
      labels:
        app: bus-service
    spec:
      containers:
        - name: bus-service
          image: pabasarasamarakoondocker1945/bus-service:latest   
          ports:
            - containerPort: 9004
          env:
            - name: DATABASE_URL
              value: postgresql://bus_service_admin:1234@bus-db:5432/bus_service_db
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: bus-service
spec:
  selector:
    app: bus-service
  ports:
    - port: 9004
      targetPort: 9004
  type: NodePort   
