apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bus-db-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bus-db
  template:
    metadata:
      labels:
        app: bus-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: bus_service_admin
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: bus_service_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: bus-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bus-db
spec:
  selector:
    app: bus-db
  ports:
    - port: 5432
      targetPort: 5432
