apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: pabasarasamarakoondocker1945/user-service:latest  
          ports:
            - containerPort: 9002
          env:
            - name: DATABASE_URL
              value: postgresql://user_service_admin:1234@user-db:5432/user_service_db
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: CORS_ORIGINS
              value: "http://127.0.0.1:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 9002
      targetPort: 9002
      nodePort: 32655
  type: NodePort   
